### PR TITLE
Probe for gtfsrt feed

### PR DESCRIPTION
**Pull request by pbougue**
Add a probe that will be used to know if the feed is OK

### CODE REVIEW

**Comment by kinnou02** [comment]
I don't understand the use case of this.

**Comment by pbougue** [comment]
To be integrated in Kirin directly (and expose result in an endpoint that will be probed)

**Comment by Madycamara** [comment]
Dépendance gtfs_realtime_pb2 à mettre dans le requirements
from google.transit import gtfs_realtime_pb2 à mettre dans le script.

**Comment by pbougue** [comment]
Not needed anymore as probe is now handled directly in Kirin and exposed in /status

**Pull request closed without merging**
